# Read more about this script on this blog post https://about.gitlab.com/2016/11/30/setting-up-gitlab-ci-for-android-projects/, by Greyson Parrelli
# https://gitlab.com/snippets/1698943
image: openjdk:8-jdk

variables:
  ANDROID_COMPILE_SDK: "28"
  ANDROID_BUILD_TOOLS: "28.0.2"
  ANDROID_SDK_ZIP_URL: "https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip"

before_script:
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1
  - wget --quiet --output-document=android-sdk.tgz ${ANDROID_SDK_ZIP_URL}
  - unzip -q -d android-sdk-linux android-sdk.tgz
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=$PATH:$ANDROID_HOME/platform-tools/
  - export PATH=$PATH:$ANDROID_HOME/tools/bin/
  - echo y | sdkmanager "platform-tools" > platform-tools.log
  - echo y | sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}" > android-sdk.log
  - echo y | sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}" > android-build-tools.log
  - echo y | sdkmanager "extras;google;m2repository" > google-repo.log
  - echo y | sdkmanager "extras;android;m2repository" > android-repo.log
  - echo y | sdkmanager "extras;google;google_play_services" > google-play-services.log
  - echo y | sdkmanager --update > update-sdk.log

  - chmod +x ./gradlew
#https://medium.com/@michalkalita/export-secret-file-to-gitlab-pipeline-75789eee35bd
  - echo $KEYSTORE_FILE | base64 -d > /builds/broachcutter/vendorapp/keystore.properties

stages:
  - build
  - test

build:
  stage: build
  script:
    - ./gradlew --no-daemon assembleDebug
  artifacts:
    paths:
    - app/build/outputs/

staticAnalysis:
  stage: test
  script:
    - ./gradlew --no-daemon detekt

unitTests:
  stage: test
  script:
    - ./gradlew --no-daemon test

#functionalTests:
#  stage: test
#  script:
#    - wget --quiet --output-document=android-wait-for-emulator https://raw.githubusercontent.com/travis-ci/travis-cookbooks/0f497eb71291b52a703143c5cd63a217c8766dc9/community-cookbooks/android-sdk/files/default/android-wait-for-emulator
#    - chmod +x android-wait-for-emulator
#    - echo y | android-sdk-linux/tools/android --silent update sdk --no-ui --all --filter sys-img-x86-google_apis-${ANDROID_COMPILE_SDK}
#    - echo no | android-sdk-linux/tools/android create avd -n test -t android-${ANDROID_COMPILE_SDK} --abi google_apis/x86
#    - android-sdk-linux/tools/emulator64-x86 -avd test -no-window -no-audio &
#    - ./android-wait-for-emulator
#    - adb shell input keyevent 82
#    - ./gradlew cAT
